# my-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: fg-apiserver
  labels:
    app: fg-apiserver  # 这个标签会被 Service 的 selector 使用
spec:
  containers:
  - name: fg-apiserver
    image: fg-apiserver:1.0
    ports:
    - containerPort: 6666  # 容器暴露的端口
      protocol: TCP
---
# my-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fg-apiserver
spec:
  type: ClusterIP  # 服务类型（默认类型，集群内部访问）
  selector:
    app: fg-apiserver    # 匹配 Pod 的标签
  ports:
    - protocol: TCP
      port: 6666     # 服务端口
      targetPort: 6666 # 目标容器端口